Integrate Paparazzi for screenshot testing

diff --git a/doc/bootstrap/git-hooks/pre-push b/doc/bootstrap/git-hooks/pre-push
--- a/doc/bootstrap/git-hooks/pre-push
+++ b/doc/bootstrap/git-hooks/pre-push
@@ -34,6 +34,11 @@ do
 	fi
 done
 
+# Git-lfs
+command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-merge.\n"; exit 2; }
+git lfs pre-push "$@"
+
+# Style check
 if [ -z "$run_checks" ]; then
     exit 0
 fi
