Fix pre-push hook to work with git-lfs
[ci skip]

diff --git a/doc/bootstrap/git-hooks/pre-push b/doc/bootstrap/git-hooks/pre-push
--- a/doc/bootstrap/git-hooks/pre-push
+++ b/doc/bootstrap/git-hooks/pre-push
@@ -20,54 +20,56 @@ set -Euo pipefail
 # This sample shows how to prevent push of commits where the log message starts
 # with "WIP" (work in progress).
 
-zero=$(git hash-object --stdin </dev/null | tr '0-9a-f' '0')
-run_checks=""
+STDIN_COPY=$(mktemp /tmp/stdincopy-XXXX)
+CHECKSTYLE_OUTPUT=$(mktemp /tmp/stylecheck-XXXX)
 
-while read local_ref local_oid remote_ref remote_oid
-do
-	if test "$local_oid" = "$zero"
-	then
-		# Handle delete
-		:
-	else
-        run_checks=true
-	fi
-done
-
-# Git-lfs
-command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-merge.\n"; exit 2; }
-git lfs pre-push "$@"
-
-# Style check
-if [ -z "$run_checks" ]; then
-    exit 0
-fi
+cleanup() {
+    trap - SIGINT SIGTERM ERR EXIT
+    rm -f "$CHECKSTYLE_OUTPUT" "$STDIN_COPY"
+}
 
 trap cleanup SIGINT SIGTERM EXIT
 
-echo "Running style check..."
-OUTPUT=$(mktemp "/tmp/stylecheck-XXXX")
+zero=$(git hash-object --stdin </dev/null | tr '0-9a-f' '0')
+run_checks=""
 
-cleanup() {
-  trap - SIGINT SIGTERM ERR EXIT
-  rm "$OUTPUT"
-}
+while read local_ref local_oid remote_ref remote_oid; do
+    if test "$local_oid" = "$zero"; then
+        # Handle delete
+        :
+    else
+        run_checks=true
+    fi
+done < <(tee "$STDIN_COPY")
 
-cd "$(git rev-parse --show-toplevel)"
+if [ -n "$run_checks" ]; then
+    # Style check
+    echo "Running style check..."
 
-./gradlew styleCheck >> "$OUTPUT" 2>&1
-GRADLE_EXIT_CODE=$?
+    cd "$(git rev-parse --show-toplevel)"
 
-dprint check >> "$OUTPUT" 2>&1
-DPRINT_EXIT_CODE=$?
+    ./gradlew styleCheck >>"$CHECKSTYLE_OUTPUT" 2>&1
+    GRADLE_EXIT_CODE=$?
 
-if [ $GRADLE_EXIT_CODE -ne 0 ] || [ $DPRINT_EXIT_CODE -ne 0 ]; then
-  cat "$OUTPUT"
-  echo "***********************************************"
-  echo "              Style check failed               "
-  echo " Please fix the above issues before committing "
-  echo "***********************************************"
-  exit 1
+    dprint check >>"$CHECKSTYLE_OUTPUT" 2>&1
+    DPRINT_EXIT_CODE=$?
+
+    if [ $GRADLE_EXIT_CODE -ne 0 ] || [ $DPRINT_EXIT_CODE -ne 0 ]; then
+        cat "$CHECKSTYLE_OUTPUT"
+        echo "***********************************************"
+        echo "              Style check failed               "
+        echo " Please fix the above issues before committing "
+        echo "***********************************************"
+        exit 1
+    fi
 fi
+
+# Git-lfs
+echo "Running git-lfs..."
+command -v git-lfs >/dev/null 2>&1 < "$STDIN_COPY" || {
+    echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-merge.\n"
+    exit 2
+}
+git lfs pre-push "$@"
 
 exit 0
